postgres:
  image: 'postgres:alpine'
  volumes:
    - postgres-volume:/var/lib/postgresql/dbClinica
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: dbClinica
    POSTGRES_HOST: postgres